name: Update readme

on:
  push:
    branches: [ "main" ] 
  pull_request:

permissions:
  contents: write  # GitHub Actions가 push할 수 있도록 권한 부여

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.10 
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-leetcode 
    - name: Run update.py
      run: python update.py
    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions@github.com'
        git add -A
        git commit -am "auto update README.md" || echo "No changes to commit"
    - name: Push changes
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/cbnuLeehyunwoo/Algorithm.git
        git push
